Silence deprecated compiler-provided copy ctor warning on Clang
We build with -Werror, but recent Clang (tested with Clang 13 on macos
12) emits this warning and the build fails:

```
googletest/googlemock/include/gmock/gmock-matchers.h:835:3: error:
  definition of implicit copy constructor for 'StartsWithMatcher<std::wstring>'
  is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
```